---
- hosts: db
  vars_files:
    - secrets.yml
  tasks:
  - name: include vars
    include_vars: secrets.yml

  - name: Add MariaDB repo to yum repo
    become: true
    copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
  
  - name: Download MariaDB server and client
    become: yes
    package: name=MariaDB-server,MariaDB-client update_cache=yes state=present
  
  - name: Start MariaDB
    become: yes
    service: name=mariadb state=started enabled=yes

  - name: Copy over the answers to the install script
    become: true
    template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

  - name: Execut the mysql secure install
    become: yes
    shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

  - name: Unarchive the database files
    become: true
    unarchive: src=db/db.tgz dest=~/ mode=0777

  - name: Run the script to create a db for the website 
    become: yes
    command: ./make_databases.sh "{{ db_password }}" web chdir=~/db
    ignore_errors: True
